import hljs from "highlight.js/lib/core";

import langBash       from "highlight.js/lib/languages/bash";
import langC          from "highlight.js/lib/languages/c";
import langCpp        from "highlight.js/lib/languages/cpp";
import langCsharp     from "highlight.js/lib/languages/csharp";
import langCss        from "highlight.js/lib/languages/css";
import langDiff       from "highlight.js/lib/languages/diff";
import langDockerfile from "highlight.js/lib/languages/dockerfile";
import langElixir     from "highlight.js/lib/languages/elixir";
import langGo         from "highlight.js/lib/languages/go";
import langHaskell    from "highlight.js/lib/languages/haskell";
import langIni        from "highlight.js/lib/languages/ini";
import langJava       from "highlight.js/lib/languages/java";
import langJs         from "highlight.js/lib/languages/javascript";
import langJson       from "highlight.js/lib/languages/json";
import langKotlin     from "highlight.js/lib/languages/kotlin";
import langLua        from "highlight.js/lib/languages/lua";
import langMakefile   from "highlight.js/lib/languages/makefile";
import langMarkdown   from "highlight.js/lib/languages/markdown";
import langNix        from "highlight.js/lib/languages/nix";
import langObjc       from "highlight.js/lib/languages/objectivec";
import langPerl       from "highlight.js/lib/languages/perl";
import langPhp        from "highlight.js/lib/languages/php";
import langPlain      from "highlight.js/lib/languages/plaintext";
import langProtobuf   from "highlight.js/lib/languages/protobuf";
import langPython     from "highlight.js/lib/languages/python";
import langR          from "highlight.js/lib/languages/r";
import langRuby       from "highlight.js/lib/languages/ruby";
import langRust       from "highlight.js/lib/languages/rust";
import langScala      from "highlight.js/lib/languages/scala";
import langShell      from "highlight.js/lib/languages/shell";
import langSql        from "highlight.js/lib/languages/sql";
import langSwift      from "highlight.js/lib/languages/swift";
import langTs         from "highlight.js/lib/languages/typescript";
import langXml        from "highlight.js/lib/languages/xml";
import langYaml       from "highlight.js/lib/languages/yaml";

hljs.registerLanguage("bash",       langBash);
hljs.registerLanguage("c",          langC);
hljs.registerLanguage("cpp",        langCpp);
hljs.registerLanguage("csharp",     langCsharp);
hljs.registerLanguage("css",        langCss);
hljs.registerLanguage("diff",       langDiff);
hljs.registerLanguage("dockerfile", langDockerfile);
hljs.registerLanguage("elixir",     langElixir);
hljs.registerLanguage("ex",         langElixir);
hljs.registerLanguage("exs",        langElixir);
hljs.registerLanguage("go",         langGo);
hljs.registerLanguage("haskell",    langHaskell);
hljs.registerLanguage("ini",        langIni);
hljs.registerLanguage("toml",       langIni);
hljs.registerLanguage("java",       langJava);
hljs.registerLanguage("javascript", langJs);
hljs.registerLanguage("js",         langJs);
hljs.registerLanguage("json",       langJson);
hljs.registerLanguage("kotlin",     langKotlin);
hljs.registerLanguage("lua",        langLua);
hljs.registerLanguage("makefile",   langMakefile);
hljs.registerLanguage("markdown",   langMarkdown);
hljs.registerLanguage("nix",        langNix);
hljs.registerLanguage("objc",       langObjc);
hljs.registerLanguage("objectivec", langObjc);
hljs.registerLanguage("perl",       langPerl);
hljs.registerLanguage("php",        langPhp);
hljs.registerLanguage("plaintext",  langPlain);
hljs.registerLanguage("protobuf",   langProtobuf);
hljs.registerLanguage("proto",      langProtobuf);
hljs.registerLanguage("python",     langPython);
hljs.registerLanguage("py",         langPython);
hljs.registerLanguage("r",          langR);
hljs.registerLanguage("ruby",       langRuby);
hljs.registerLanguage("rb",         langRuby);
hljs.registerLanguage("rust",       langRust);
hljs.registerLanguage("rs",         langRust);
hljs.registerLanguage("scala",      langScala);
hljs.registerLanguage("shell",      langShell);
hljs.registerLanguage("sh",         langBash);
hljs.registerLanguage("sql",        langSql);
hljs.registerLanguage("swift",      langSwift);
hljs.registerLanguage("typescript", langTs);
hljs.registerLanguage("ts",         langTs);
hljs.registerLanguage("xml",        langXml);
hljs.registerLanguage("html",       langXml);
hljs.registerLanguage("yaml",       langYaml);
hljs.registerLanguage("yml",        langYaml);

export default hljs;
